# Generated by Django 5.1.1 on 2024-09-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('ethereum_address', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
