# Generated by Django 5.1.1 on 2024-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='transaction_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=10),
        ),
    ]
